fix version of ActiveRecord::Migration
This fix specifies which version of ActiveRecord::Migration to inherit from.

From rails version 5.1, db migration fails with following error:
 Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
 class CreateStoriesTasksSprintsAndBurndown < ActiveRecord::Migration[4.2]
 Caused by:
 StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: